services:
  postgres:
    image: 'postgres:latest'
    container_name: advertisement
    environment:
      - POSTGRES_DB=advertisement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    container_name: "redis-advertisement"
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:

