INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(2, 'Strollers', 'Коляски прогулянкові', 12),
(2, 'Newborn Strollers', 'Коляски для новонароджених', 12),
(2, 'Car Seats', 'Автокрісла', 12),
(2, 'Stroller and Car Seat Toys', 'Іграшки для колясок та автокрісел', 12),
(2, 'Other', 'Інше', 12),
(2, 'Building Blocks', 'Конструктори', 13),
(2, 'Dolls and Stuffed Animals', 'Ляльки та пупси', 13),
(2, 'Blocks and Pyramids', 'Кубики та пірамідки', 13),
(2, 'Soft Toys', 'М''які іграшки', 13),
(2, 'Toy Vehicles', 'Іграшковий транспорт, машинки і техніка', 13),
(2, 'Teething Toys and Mobiles', 'Брязкальця та підвіски, мобілі', 13),
(2, 'Puzzles and Board Games', 'Пазли та настільні ігри', 13),
(2, 'Educational Toys', 'Розвиваючі іграшки', 13),
(2, 'Balls', 'М''ячі', 13),
(2, 'Bath Toys', 'Іграшки для купання', 13),
(2, 'Toy Weapons', 'Іграшкова зброя', 13),
(2, 'Play Sets', 'Ігрові набори', 13),
(2, 'Sand Toys', 'Іграшки для піску', 13),
(2, 'Other Toys', 'Інші іграшки', 13),
(2, 'Interactive and Musical Toys', 'Інтерактивні та музичні іграшки', 13),
(2, 'Creative Sets', 'Творчі набори', 13),
(2, 'Backpacks, Bags, and Satchels', 'Рюкзаки, сумки та ранці', 14),
(2, 'Stationery', 'Канцелярія', 14),
(2, 'Art Supplies', 'Товари для творчості', 14),
(2, 'Sets', 'Набори', 14),
(2, 'Textbooks and Workbooks', 'Підручники та посібники', 14),
(2, 'Atlases, Maps, and Exercise Books', 'Атласи, карти, зошити з друкованою основою', 14),
(2, 'Lunch Boxes and Water Bottles', 'Ланчбокси та пляшки для води', 14),
(2, 'Sports Equipment', 'Спортивне спорядження', 14),
(2, 'School Accessories', 'Аксесуари для школи', 14),
(2, 'Other School Supplies', 'Інші товари для школярів', 14),
(2, 'Cribs and Cradles', 'Ліжечка та люльки', 15),
(2, 'Cradles', 'Люльки', 15),
(2, 'High Chairs', 'Стілець для годування', 15),
(2, 'Toy Chests', 'Комоди для іграшок', 15),
(2, 'Wardrobes', 'Шафи', 15),
(2, 'Playpens', 'Манежі', 15),
(2, 'Children''s Tables and Chairs', 'Дитячі столи та стільці', 15),
(2, 'Furniture Accessories', 'Аксесуари для дитячих меблів', 15),
(2, 'Other Children''s Furniture', 'Інші дитячі меблі', 15),
(2, 'Scooters', 'Самокати', 16),
(2, 'Bicycles', 'Велосипеди', 16),
(2, 'Skates and Rollerblades', 'Ролики та коньки', 16),
(2, 'Skateboards', 'Скейти', 16),
(2, 'Electric Cars', 'Електромобіль', 16),
(2, 'Push Cars', 'Толкар', 16),
(2, 'Walkers', 'Ходунки', 16),
(2, 'Other Children''s Transport', 'Інший дитячий транспорт', 16),
(2, 'Pacifiers and Teethers', 'Пустушки та соски', 17),
(2, 'Bottles', 'Пляшечки', 17),
(2, 'Sippy Cups', 'Поїльники', 17),
(2, 'Baby Food Makers', 'Дитячі кухонні комбайни', 17),
(2, 'Sterilizers and Warmers', 'Стерилізатори та підігрівачі', 17),
(2, 'Bib and Aprons', 'Слюнявчики та нагрудники', 17),
(2, 'Feeding Accessories', 'Аксесуари для дитячого посуду', 17),
(2, 'Nipplers', 'Ніблери', 17),
(2, 'Thermoses', 'Термоси', 17),
(2, 'Tableware', 'Посуд', 17),
(2, 'Other Feeding Items', 'Інше в годування', 17),
(2, 'Diapers and Nappies', 'Підгузки та пелюшки', 18),
(2, 'Bath Products', 'Засоби для купання', 18),
(2, 'Skin and Hair Care', 'Догляд за шкірою та волоссям', 18),
(2, 'Cleaning Products for Nursery', 'Товари для прибирання дитячої кімнати', 18),
(2, 'Hygiene Products (Sponges, Wipes, Swabs)', 'Гігієнічні товари ( спонжі, серветки, палички)', 18),
(2, 'Other', 'Інше', 18),
(2, 'Backpacks and Bags', 'Рюкзаки та сумки', 19),
(2, 'Watches and Jewelry', 'Годинники та прикраси', 19),
(2, 'Glasses and Headwear', 'Окуляри та головні убори', 19),
(2, 'Umbrellas and Raincoats', 'Парасольки та дощовики', 19),
(2, 'Other Accessories', 'інші аксесуари', 19),
(2, 'Sports Equipment', 'Спортивний інвентар', 20),
(2, 'Bicycles and Bicycle Parts', 'Велосипеди та запчастини до них', 20),
(2, 'Bike Accessories', 'Велоаксесуари', 20),
(2, 'Sledges and Snow Sleds', 'Санки та снігокати', 20),
(2, 'Snow Tubes and Saucers', 'Льодянки та тарілки', 20),
(2, 'Skates and Skateboards', 'Ковзани, ролики та скейти', 20),
(2, 'Skateboards and Scooters', 'Скейти та самокати', 20),
(2, 'Skis', 'Лижі', 20),
(2, 'Jumpers', 'Джампери', 20),
(2, 'Swings', 'Гойдалки', 20),
(2, 'Trampolines', 'Батути', 20),
(2, 'Swimming Gear', 'Товари для плавання', 20),
(2, 'Protective Gear', 'Захист', 20),
(2, 'Other', 'Інше', 20);