INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(3, 'Fiction', 'Художні', 22),
(3, 'Children''s Books', 'Дитячі', 22),
(3, 'Scientific', 'Наукові', 22),
(3, 'Magazines', 'Журнали', 22),
(3, 'Business', 'Бізнес', 22),
(3, 'Psychology', 'Психологія', 22),
(3, 'Historical', 'Історичні', 22),
(3, 'Cookbooks', 'Кулінарні', 22),
(3, 'Dictionaries', 'Словники', 22),
(3, 'Home and Hobbies', 'Дім та хоббі', 22),
(3, 'Other Books and Magazines', 'Інші книги та журнали', 22),
(3, 'Collectibles', 'Колекціонування', 23),
(3, 'Handmade Artifacts', 'Витвори майстрів/рукоділля', 23),
(3, 'Painting', 'Живопис', 23),
(3, 'Numismatics', 'Нумізматика', 23),
(3, 'Philately', 'Філателія', 23),
(3, 'Old and Rare Books', 'Букіністика', 23),
(3, 'Art Objects', 'Предмети мистецтва', 23),
(3, 'Antique Furniture', 'Антикварні меблі', 23),
(3, 'Rare Items', 'Рарітетні речі', 23),
(3, 'Other Collectibles/Antiques', 'Інше в колекціонування та антикваріат', 23),
(3, 'Flashlights', 'Ліхтарики', 24),
(3, 'Gas Burners and Portable Gas Stoves', 'Газові пальники, портативні газові плити', 24),
(3, 'Gas Cylinders', 'Газові балони', 24),
(3, 'Sleeping Bags, Mats, and Carpets', 'Спальні мішки. килимки, карімати', 24),
(3, 'Tents', 'Палатки', 24),
(3, 'Backpacks', 'Рюкзаки', 24),
(3, 'GPS Navigators', 'GPS навігатори', 24),
(3, 'Foldable Furniture', 'Складні меблі', 24),
(3, 'Camping Tableware', 'Посуд для туризму та відпочинку', 24),
(3, 'Thermal Products', 'Термопродукція', 24),
(3, 'Grills and Barbecues', 'Мангали та барбекю', 24),
(3, 'Tactical Medicine', 'Тактична медицина', 24),
(3, 'Accessories', 'Аксесуари', 24),
(3, 'Other Tourism and Camping Goods', 'Інші туристичні товари', 24),
(3, 'Fishing Rods and Spinning Rods', 'Вудки, спінінги', 25),
(3, 'Reels', 'Котушки', 25),
(3, 'Lures', 'Воблери', 25),
(3, 'Lures and Spinners', 'Блешня', 25),
(3, 'Soft Baits', 'М''які приманки', 25),
(3, 'Hooks', 'Гачки', 25),
(3, 'Swivels and Clips', 'Вертлюги і застібки', 25),
(3, 'Feeders', 'Годівниці', 25),
(3, 'Weights', 'Грузила', 25),
(3, 'Accessories', 'Аксесуари', 25),
(3, 'Other Fishing Items', 'Інше в риболовля', 25),
(3, 'Studio Equipment', 'Студійне обладнання', 26),
(3, 'Instrument Accessories', 'Аксесуари для музичних інструментів', 26),
(3, 'String Instruments', 'Струнні музичні інструменти', 26),
(3, 'Wind Instruments', 'Духові інструменти', 26),
(3, 'Pianos and Grand Pianos', 'Піаніно/ фортепіано/ роялі', 26),
(3, 'Synthesizers', 'Синтезатори', 26),
(3, 'Percussion Instruments', 'Ударні інструменти', 26),
(3, 'Amplifiers', 'Комбопідсилювачі', 26),
(3, 'Other Musical Instruments', 'Інше', 26),
(3, 'Paint by Numbers', 'Картини по номерам', 27),
(3, 'Board Games', 'Настільні ігри', 27),
(3, 'Crafts', 'Рукоділля', 27),
(3, 'Drawing/Painting Supplies', 'Все для малювання/живопису', 27),
(3, 'Stationery and Creative Supplies', 'Канцтовари і товари для творчості', 27),
(3, 'Other Leisure Goods', 'Інші товари для дозвілля', 27),
(3, 'Boats', 'Човни', 28),
(3, 'Boat Accessories', 'Аксесуари для човнів', 28),
(3, 'Other Boats and Accessories', 'Інше в човни та аксесуари', 28),
(3, 'All Drones and Accessories', 'Все в квадрокоптери та аксесуари', 29),
(3, 'Drones', 'Квадрокоптери', 29),
(3, 'Drone Accessories', 'Аксесуари для квадрокоптерів', 29),
(3, 'Other Drones and Accessories', 'Інше', 29),
(3, 'Military Clothing', 'Військовий одяг', 30),
(3, 'Gear', 'Спорядження', 30),
(3, 'Military Footwear', 'Військове взуття', 30),
(3, 'Weapon Accessories', 'Збройові аксесуари', 30),
(3, 'Backpacks and Bags', 'Рюкзаки та сумки', 30),
(3, 'Load Carrying Systems', 'Розвантажувальні системи', 30),
(3, 'Pouches', 'Підсумки', 30),
(3, 'Medical Supplies', 'Медицина', 30),
(3, 'Protection', 'Захист', 30),
(3, 'Other Militaria', 'Інше в мілітарія', 30),
(3, 'Football', 'Футбол', 31),
(3, 'Athletics and Fitness', 'Атлетика та фітнес', 31),
(3, 'Martial Arts', 'Єдиноборства', 31),
(3, 'Water Sports', 'Водні види спорту', 31),
(3, 'Winter Sports', 'Зимні види спорту', 31),
(3, 'Racket Games', 'Ігри з ракеткою', 31),
(3, 'Hockey', 'Хокей', 31),
(3, 'Exercise Machines', 'Тренажери', 31),
(3, 'Sports Nutrition', 'Спортивне харчування', 31),
(3, 'Other Sports Goods', 'Інші спортивні товари', 31);