INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(4, 'Electric Cars', 'Електромобілі', 34),
(4, 'Mechanical Transmission', 'Механіка', 34),
(4, 'Automatic Transmission', 'Автомат', 34),
(4, 'Other Passenger Cars', 'Інші легкові авто', 34),
(4, 'Motorcycles', 'Мотоцикли', 36),
(4, 'Electric Scooters/Gyros', 'Електросамокати/гіроскутери', 36),
(4, 'Mopeds/Scooters', 'Мопеди/скутери', 36),
(4, 'ATVs', 'Квадроцикли', 36),
(4, 'Electric Scooters', 'Електроскутери', 36),
(4, 'Buggies', 'Баггі', 36),
(4, 'Go-Karts', 'Картинг', 36),
(4, 'Moto Gear', 'Мотоспорядження', 36),
(4, 'Moto Accessories', 'Мотоаксесуари', 36),
(4, 'Other Moto', 'Інше', 36),
(4, 'Attachments and Additional Equipment', 'Навісне та додаткове обладнання', 37),
(4, 'Mini Tractors', 'Мінітрактор', 37),
(4, 'Agricultural Tractors', 'Трактор сількогосподарський', 37),
(4, 'Other Agricultural Machinery', 'Інша сільгосптехніка', 37),
(4, 'Power Harrows', 'Мотоблок', 37),
(4, 'Harvesters', 'Комбайн', 37),
(4, 'Cultivators', 'Мотокультиватор', 37),
(4, 'Bulldozers/Tractors', 'Бульдозери/трактори', 38),
(4, 'Cranes and Manipulators', 'Автокрани та маніпулятори', 38),
(4, 'Loaders', 'Навантажувачі', 38),
(4, 'Excavators', 'Ескаватори', 38),
(4, 'Special Machinery Equipment', 'Обладнання для спецтехніки', 38),
(4, 'Other Special Machinery', 'Інша спецтехніка', 38),
(4, 'Tires, Rims and Wheels', 'Шини, диски та колеса', 39),
(4, 'Engines and Parts', 'Двигуни та деталі', 39),
(4, 'Auto Filters', 'Автофільтри', 39),
(4, 'Braking System', 'Гальмівна система', 39),
(4, 'Suspension', 'Підвіска автомобіля', 39),
(4, 'Body Parts', 'Кузовні запчастини', 39),
(4, 'Ignition System', 'Система запалювання', 39),
(4, 'Lighting Devices', 'Світлові прилади', 39),
(4, 'Cooling System', 'Система охолодження двигуна', 39),
(4, 'Fuel System', 'Паливна система', 39),
(4, 'Transmission and Clutch', 'Трансмісія та зчеплення', 39),
(4, 'Air Conditioning and Heating', 'Кондиціонування та опалення', 39),
(4, 'Electrical Equipment', 'Електрообладнання', 39),
(4, 'Car Audio', 'Автозвук', 39),
(4, 'Interior', 'Інтер''єр автомобіля', 39),
(4, 'Car Tuning', 'Автотюнінг', 39),
(4, 'Car Roof Racks', 'Автомобільні багажники', 39),
(4, 'Auxiliary Equipment', 'Допоміжне обладнання', 39),
(4, 'Transport Parts', 'Транспорт на запчастини', 39),
(4, 'Other Spare Parts', 'Інші запчастини', 39),
(4, 'All Automotive Electronics', 'Все в автомільна електроніка', 40),
(4, 'Dash Cameras', 'Відеореєстратори', 40),
(4, 'Parking Systems', 'Паркувальні системи', 40),
(4, 'Car Video Systems', 'Автомобільні відеосистеми', 40),
(4, 'GPS Navigators', 'GPS - навігатори', 40),
(4, 'Anti-Theft Systems', 'Протиугінні системи', 40),
(4, 'Seat and Mirror Heaters', 'Підігрів сидінь та зеркал', 40),
(4, 'On-Board Computers', 'Бортові комп''ютери', 40),
(4, 'Car Vacuums', 'Автомобільні пилососи', 40),
(4, 'Car Inverters', 'Автомобільні інвертори', 40),
(4, 'Car Refrigerators', 'Автохолодильники', 40),
(4, 'Jump Starters and Chargers', 'Пускові та зарядні пристрої', 41),
(4, 'Car Mats', 'Автоковрики', 41),
(4, 'Car Compressors, Pumps, Manometers', 'Автокомпресори, насоси манометри', 41),
(4, 'Car Tools and Wrench Sets', 'Автоінструменти, набори ключів', 41),
(4, 'Fasteners', 'Елементи кріплення', 41),
(4, 'Thresholds and Pads', 'Пороги та накладки', 41),
(4, 'Canisters', 'Каністри', 41),
(4, 'Covers, Tarps, and Covers', 'Чохли, тенти та накидки', 41),
(4, 'Stickers, Emblems, and Badges', 'Наклейки, емблеми та значки', 41),
(4, 'Tow Bars', 'Фаркопи', 41),
(4, 'Stands and Holders', 'Підставки та тримачі', 41),
(4, 'Tuning', 'Тюнінг', 41),
(4, 'Jacks', 'Домкрати', 41),
(4, 'Organizers', 'Органайзери', 41),
(4, 'Car Curtains', 'Автошторки', 41),
(4, 'Deflectors', 'Дефлектори', 41),
(4, 'Car Alarms and Immobilizers', 'Автосигналізація, блокувачі', 41),
(4, 'Air Fresheners and Ozonizers', 'Ароматизатори, озонатори', 41),
(4, 'Fire Extinguishers, First Aid Kits, Emergency Kits', 'Вогнегасники, аптечка, аварійка', 41),
(4, 'Mud Flaps', 'Бризковики', 41),
(4, 'Wipers and Scrapers', 'Щітки, скребки', 41),
(4, 'Car Cushions', 'Автоподушки', 41),
(4, 'Other Accessories', 'Інші аксесуари', 41),
(4, 'Car Chemicals', 'Автохімія', 42),
(4, 'Car Oils', 'Автомастила', 42),
(4, 'Car Cosmetics', 'Автокосметика', 42),
(4, 'Other Car Chemicals', 'Інші автохімія', 42);