INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(5, 'Phone Accessories', 'Аксесуари для телефонів', 44),
(5, 'Mobile Phones and Smartphones', 'Мобільні телефони та смартфони', 44),
(5, 'Landline Phones', 'Стаціонарні телефони', 44),
(5, 'Phone Parts', 'Запчастини для телефонів', 44),
(5, 'Radios and Other Phones', 'Рації та інші телефони', 44),
(5, 'SIM Cards/Tariffs/Numbers', 'Сім-карти/ тарифи/номери', 44),
(5, 'Power Banks and Accessories', 'Павербанки та комплектуючі', 44),
(5, 'Other Phone Accessories', 'Інше в телефони та аксесуари', 44),
(5, 'Headphones', 'Навушники', 45),
(5, 'Sound Systems', 'Акустичні системи', 45),
(5, 'Portable Speakers', 'Портативна акустика', 45),
(5, 'Amplifiers/Receivers', 'Підсилювачі/ресивери', 45),
(5, 'CD/MD/Vinyl Players', 'CD/md/вінілові програвачі', 45),
(5, 'Radio Receivers', 'Радіоприймачі', 45),
(5, 'Car Radios', 'Магнітоли', 45),
(5, 'MP3 Players', 'MP3 плеєри', 45),
(5, 'Music Centers', 'Музичні центри', 45),
(5, 'Other Audio Equipment', 'Інша аудіотехніка', 45),
(5, 'Peripheral Devices', 'Периферійні пристрої', 46),
(5, 'Components and Accessories', 'Комплектуючі та аксесуари', 46),
(5, 'Desktop Computers', 'Настільні комп''ютери', 46),
(5, 'Monitors', 'Монітори', 46),
(5, 'Consumables', 'Витратні матеріали', 46),
(5, 'External Storage', 'Зовнішні накопичувачі', 46),
(5, 'Servers', 'Сервери', 46),
(5, 'Other Computers and Components', 'Інше і комп''ютери та комплектуючі', 46),
(5, 'Game Heroes', 'Герої ігор', 47),
(5, 'Consoles', 'Приставки', 47),
(5, 'Accessories', 'Аксесуари', 47),
(5, 'Console Games', 'Ігри для приставок', 47),
(5, 'PC Games', 'Ігри для ЗС', 47),
(5, 'Other Games and Consoles', 'Інше', 47),
(5, 'Voltage Converters', 'Перетворювачі напруги', 48),
(5, 'Sewing Machines and Overlocks', 'Швейні машини та оверлоки', 48),
(5, 'Washing Machines', 'Пральні машини', 48),
(5, 'Vacuum Cleaners', 'Пилососи', 48),
(5, 'Uninterruptible Power Supplies', 'Безперебійники живлення', 48),
(5, 'Charging Stations', 'Зарядні станції', 48),
(5, 'Irons', 'Праски', 48),
(5, 'Washing Machine Parts', 'Запчастини до пральних машин', 48),
(5, 'Water Filters', 'Фільтри для води', 48),
(5, 'Other Home Appliances', 'Інша техніка для дому', 48),
(5, 'Coffee Makers/Coffee Grinders', 'Кавоварки/кавомолки', 49),
(5, 'Refrigerators', 'Холодильники', 49),
(5, 'Cookers/Ovens', 'Плити / печі', 49),
(5, 'Food Processors and Choppers', 'Кухонні комбайни та подрібнювачі', 49),
(5, 'Steamers, Multicookers, Electric Grills', 'Пароварки, мультиварки, електрогрилі', 49),
(5, 'Microwave Ovens', 'Мікрохвильові печі', 49),
(5, 'Electric Kettles', 'Електрочайники', 49),
(5, 'Dishwashers', 'Посудомийні машини', 49),
(5, 'Hoods', 'Витяжки', 49),
(5, 'Refrigerator Parts', 'Запчастини до холодильників', 49),
(5, 'Bread Makers', 'Хлібопічки', 49),
(5, 'Other Kitchen Appliances', 'Інша техніка для кухні', 49),
(5, 'Televisions', 'Телевізори', 50),
(5, 'TV/Video Accessories', 'Аксесуари для ТВ / відеотехніки', 50),
(5, 'Media Players', 'Медіа програвачі', 50),
(5, 'Projectors', 'Проектори', 50),
(5, 'Satellite TV', 'Супутникове ТВ', 50),
(5, 'Other TV/Video Equipment', 'Інша ТВ /відеотехніка', 50),
(5, 'Digital Cameras', 'Цифрові фотоапарати', 51),
(5, 'Photo/Video Accessories', 'Аксесуари для фото / відеокамер', 51),
(5, 'Film Cameras', 'Плівкові фотоапарати', 51),
(5, 'Lenses', 'Об''єктиви', 51),
(5, 'Telescopes/Binoculars', 'Телескопи / біноклі', 51),
(5, 'Camcorders', 'Відеокамери', 51),
(5, 'Tripods/Monopods', 'Штативи / моноподи', 51),
(5, 'Action Cameras', 'Екшн-камери', 51),
(5, 'Flashes', 'Фотоспалахи', 51),
(5, 'Other Photo/Video', 'Інше в Фото/відео', 51),
(5, 'All Tablets/E-books', 'Все в Планшети / ел. книги', 52),
(5, 'Tablets', 'Планшетні комп''ютери', 52),
(5, 'Tablet/E-book Accessories', 'Аксесуари для планшетів / ел. книг', 52),
(5, 'Graphic Tablets', 'Графічні планшети', 52),
(5, 'Tablet/E-book Parts', 'Запчастини для планшетів / ел. книг', 52),
(5, 'E-books', 'Електронні книги', 52),
(5, 'Other Tablets/E-books', 'Іншіе в Планшети/ ел. книги', 52),
(5, 'All Climate Equipment', 'Все в Кліматичне обладнання', 53),
(5, 'Wall Air Conditioners', 'Настінні кондиціонери', 53),
(5, 'Floor Air Conditioners', 'Напольні кондиціонери', 53),
(5, 'Air Purifiers', 'Очисники повітря', 53),
(5, 'Humidifiers', 'Зволожувачі повітря', 53),
(5, 'Climate Equipment Accessories and Parts', 'Аксесуари та запчастини для кліматичного обладнання', 53),
(5, 'Other Climate Equipment', 'Інші товари', 53),
(5, 'All Personal Care', 'Все в Індивідуальний догляд', 54),
(5, 'Hair Dryers, Hair Styling Tools', 'Фени, укладка волосся', 54),
(5, 'Razors, Epilators, Hair Clippers', 'Бритви, епілятори, машинки для стрижки', 54),
(5, 'Scales', 'Ваги', 54),
(5, 'Massagers', 'Масажери', 54),
(5, 'Electric Toothbrushes, Irrigators', 'Електро зубні щітки, іррігатори', 54),
(5, 'Other Personal Care Devices', 'Інші техніка для догляду', 54);
