INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(9, 'Manicure and Pedicure', 'Манікюр та педікюр', 76),
(9, 'Eyelashes and Eyebrows', 'Вії та брови', 76),
(9, 'Massage', 'Масаж', 76),
(9, 'Hairdressing Services', 'Перукарські послуги', 76),
(9, 'Psychological Services', 'Послуги психолога', 76),
(9, 'Medical Services', 'Медичні послуги', 76),
(9, 'Tattoos, Piercing', 'Тату, татуаж, пірсинг', 76),
(9, 'Hair Removal', 'Видалення волосся', 76),
(9, 'Cosmetic Services', 'Косметологічні послуги', 76),
(9, 'Make-up', 'Візаж та макіяж', 76),
(9, 'Baths, Saunas, Spa', 'Лазні, сауни та SPA', 76),
(9, 'Other Beauty Services', 'Інші бюті послуги', 76),
(9, 'Freight Transport', 'Вантажоперевезення', 77),
(9, 'Passenger Transport', 'Пасажирські перевезення', 77),
(9, 'Tow Truck and Car Transport Services', 'Послуги евакуатора та автовозу', 77),
(9, 'Crane Services', 'Послуги маніпулятора', 77),
(9, 'Loading Services', 'Послуги вантажників', 77),
(9, 'Driver Services', 'Послуги водіїв', 77),
(9, 'Other Transport Services', 'Інші транспортні послуги', 77),
(9, 'Industrial Equipment', 'Промислове обладнання', 78),
(9, 'Trade Show Equipment', 'Торгово-виставкове обладнання', 78),
(9, 'Refrigeration Equipment', 'Холодильне обладнання', 78),
(9, 'Medical Equipment', 'Медичне обладнання', 78),
(9, 'Restaurant and Cafe Equipment', 'Обладнання для ресторанів і кафе', 78),
(9, 'Beauty Salon Equipment', 'Обладнання для салонів краси', 78),
(9, 'Cash Register Equipment', 'Розрахунково-касове обладнання', 78),
(9, 'Laboratory Equipment', 'Лабораторне обладнання', 78),
(9, 'Other Business Equipment', 'Інше обладнання', 78),
(9, 'Construction Services', 'Будівельні послуги', 79),
(9, 'Finishing and Repair', 'Оздоблення та ремонт', 79),
(9, 'Dismantling Work', 'Демонтажні роботи', 79),
(9, 'Plumbing and Utilities', 'Сантехніка та комунікації', 79),
(9, 'Design and Projecting', 'Проектування та дизайн', 79),
(9, 'Electrical Installation Services', 'Електромонтажні послуги', 79),
(9, 'Ready-Made Structures', 'Готові конструкції', 79),
(9, 'Window, Door, Balcony Installation', 'Монтаж вікон, дверей, балконів', 79),
(9, 'Turnkey Repair', 'Ремонт під ключ', 79),
(9, 'Turnkey Construction', 'Будівництво під ключ', 79),
(9, 'Drilling Wells', 'Буріння свердловин', 79),
(9, 'Welding Work', 'Зварювальні роботи', 79),
(9, 'Ventilation and Air Conditioning', 'Вентиляція та кондиціонування', 79),
(9, 'Landscaping and Earthworks', 'Ландшафтні та земельні роботи', 79),
(9, 'Security Systems Installation and Repair', 'Встановлення та ремонт систем безпеки', 79),
(9, 'Other Services', 'Інші послуги', 79),
(9, 'Waste Collection', 'Вивезення сміття', 80),
(9, 'Clothing Alteration and Repair', 'Пошиття та ремонт одягу', 80),
(9, 'Gardening and Landscaping Services', 'Послуги садівництва та догляду за територією', 80),
(9, 'Disinfection and Pest Control', 'Дезинфекція та дезинсекція', 80),
(9, 'Septic Tank Services', 'Послуги асенізатора', 80),
(9, 'Dry Cleaning and Laundry', 'Хімчистка та прання', 80),
(9, 'Emergency Lock Opening', 'Аварійне відкриття замків', 80),
(9, 'Shoe and Bag Repair', 'Ремонт взуття та сумок', 80),
(9, 'Key Making', 'Виготовлення ключів', 80),
(9, 'Chef Services', 'Послуги повара', 80),
(9, 'Housekeeping Services', 'Послуги прибиральниці', 80),
(9, 'Other Household Services', 'Інші побутові послуги', 80),
(9, 'Tutors', 'Репетитори', 81),
(9, 'Child Development, Logopedists, Psychologists', 'Дитячий розвиток, логопеди, психологи', 81),
(9, 'Courses and Training', 'Курси та тренінги', 81),
(9, 'Driving Instructors', 'Автоінструктори', 81),
(9, 'Music and Vocal Teachers', 'Викладачі музики та вокалу', 81),
(9, 'Sports and Dance', 'Спорт і танці', 81),
(9, 'Personal Development (Public Speaking, Coaching, etc.)', 'Особистісний зріст (ораторське мистецтво, коучінг і т.д.)', 81),
(9, 'Other Education Services', 'Інше в послуги освіти', 81),
(9, 'Household Appliances', 'Побутова техніка', 83),
(9, 'Photo and Video Equipment', 'Фото і відеоапаратура', 83),
(9, 'Computer Equipment', 'Комп''ютерна техніка', 83),
(9, 'Climate Equipment', 'Кліматична техніка', 83),
(9, 'TV and Video Equipment', 'ТВ і відеотехніка', 83),
(9, 'Phones and Smartphones', 'Телефони і смартфони', 83),
(9, 'Electrical and Gas Tools', 'Електро та бензоінструмент', 83),
(9, 'Electric Transport', 'Електротранспорт', 83),
(9, 'Audio Equipment', 'Аудіотехніка', 83),
(9, 'Game Consoles', 'Ігрові приставки', 83),
(9, 'Office Equipment, Cartridge Refilling', 'Оргтехніка, заправка картриджів', 83),
(9, 'Other Equipment', 'Інша техніка', 83),
(9, 'Legal Services', 'Юридичні послуги', 84),
(9, 'Financial Services, Partnerships', 'Фінансові послуги, партнерство', 84),
(9, 'Marketing Services', 'Маркетингові послуги', 84),
(9, 'Printing, Advertising, Design', 'Поліграфія, реклама, друк', 84),
(9, 'Website Development', 'Створення сайтів', 84),
(9, 'Accounting Services', 'Бухгалтерські послуги', 84),
(9, 'Translation, Typing Services', 'Послуги перекладачів, набір тексту', 84),
(9, 'Other Business Services', 'Інші ділові послуги', 84),
(9, 'Catering, Chefs', 'Кейтерінг, кухарі', 85),
(9, 'Animators and Mascots', 'Аніматори та ростові ляльки', 85),
(9, 'Custom Desserts and Pastries', 'Десерти та випічка на замовлення', 85),
(9, 'Hosts, Musicians, Toastmasters', 'Ведучі, музиканти, тамада', 85),
(9, 'Decoration, Balloons, Flowers', 'Декор, оформлення кульками, квітами', 85),
(9, 'Other Event Services', 'Інші послуги для свят', 85),
(9, 'Shops', 'Магазини', 86),
(9, 'Cafes, Restaurants, Coffee Shops', 'Кафе, ресторани, кав''ярні', 86),
(9, 'Social Media Accounts', 'Акаунти в соцмережах', 86),
(9, 'Enterprises, Companies', 'Підприємства, компанії', 86),
(9, 'Online Stores', 'Інтернет-магазини', 86),
(9, 'Franchises', 'Франшизи', 86),
(9, 'Other Business Types', 'Інші види бізнесу', 86),
(9, 'Photography and Photo Retouching', 'Фотозйомка та ретуш фото', 87),
(9, 'Video Shooting and Editing', 'Відеозйомка та монтаж відео', 87),
(9, 'Other Photo/Video Services', 'Інші фото та відео послуги', 87),
(9, 'Digitizing and Restoration', 'Оцифрування та реставрація', 87),
(9, 'Industrial Cleaning', 'Промисловий клінінг', 88),
(9, 'Window Cleaning', 'Миття вікон', 88),
(9, 'Regular Maintenance Cleaning', 'Підтримуючі регулярні прибирання', 88),
(9, 'Carpet and Furniture Cleaning', 'Хімчистка килимів та меблів', 88),
(9, 'Car Cleaning', 'Хімчистка авто', 88),
(9, 'Disinfection and Pest Control', 'Дезинфекція та дезинсекція', 88),
(9, 'Other Cleaning Services', 'Інше в клінінг', 88),
(9, 'All Pet Services', 'Все в послуги для тварин', 90),
(9, 'Breeding', 'В''язка', 90),
(9, 'Grooming', 'Грумінг', 90),
(9, 'Training and Obedience', 'Тренування, дресирування', 90),
(9, 'Pet Sitting and Boarding', 'Перетримка, готелі для тварин', 90),
(9, 'Veterinary Services', 'Медичні послуги для тварин', 90),
(9, 'Dog Walking', 'Вигул', 90),
(9, 'Other Pet Services', 'Інше в послуги для тварин', 90),
(9, 'Nanny', 'Няня', 91),
(9, 'Caregiver', 'Доглядальниця', 91),
(9, 'Other Child/Elderly Care', 'Інше', 91),
(9, 'Monument Making', 'Виготовлення пам''ятників', 92),
(9, 'Other Funeral Services', 'Інші ритуальні послуги', 92),
(9, 'Visa Services', 'Оформлення віз', 93),
(9, 'Tours and Excursions', 'Тури та екскурсії', 93),
(9, 'Other Tourism Services', 'Інші послуги туризму', 93);