INSERT INTO subcategories (category_id, name_en, name_ukr)
VALUES
    (6, 'Retail / Sales / Procurement', 'Роздрібна торгівля / продажі / закупки'),
    (6, 'Logistics / Warehouse / Delivery', 'Логістика / Склад / Доставка'),
    (6, 'Construction', 'Будівництво'),
    (6, 'Call Centers / Telecommunications', 'Колл-центри / Телекомунікації'),
    (6, 'Administrative Staff / HR / Secretariat', 'Адміністративний персонал / HR / Секретаріат'),
    (6, 'Security', 'Охорона / безпека'),
    (6, 'Cleaning / Domestic Staff', 'Клінінг / Домашній персонал'),
    (6, 'Beauty / Fitness / Sports', 'Краса / фітнес / спорт'),
    (6, 'Education / Translation', 'Освіта / переклад'),
    (6, 'Culture / Arts / Entertainment', 'Культура / мистецтво / розваги'),
    (6, 'Medicine / Pharmaceuticals', 'Медицина / фармацевтика'),
    (6, 'IT / Computers', 'IT / комп''ютери'),
    (6, 'Banks / Finance / Insurance / Law', 'Банки / фінанси / страхування / юриспруденція'),
    (6, 'Real Estate', 'Нерухомість'),
    (6, 'Advertising / Design / PR', 'Реклама / дизайн / PR'),
    (6, 'Manufacturing / Working Specialties', 'Виробництво / робітничі спеціальності'),
    (6, 'Agriculture / Forestry / Agribusiness', 'Сільське і лісове господарство / агробізнес'),
    (6, 'Part-Time Employment', 'Часткова зайнятість'),
    (6, 'Start of Career / Students', 'Початок кар''єри / Студенти'),
    (6, 'Work Abroad', 'Робота за кордоном'),
    (6, 'Accounting', 'Бухгалтерія'),
    (6, 'Hotel-Restaurant Business / Tourism', 'Готельно-ресторанний бізнес / Туризм'),
    (6, 'Other Fields', 'Інші сфери занять'),
    (6, 'Car Service / Car Wash', 'СТО / автомийки'),
    (6, 'Service in the Defense Forces', 'Служба в Силах оборони');