INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(12, 'Passenger Cars Rentals', 'Оренда легкових авто', 122),
(12, 'Bus and Minibus Rentals', 'Автобус, мікроавтобус', 122),
(12, 'Aerial Platform Rentals', 'Автовишка', 122),
(12, 'Trailer Rentals', 'Причеп', 122),
(12, 'Excavator and Bulldozer Rentals', 'Ескаватор, бульдозер', 122),
(12, 'Crane Rentals', 'Кран', 122),
(12, 'Tractor and Combine Rentals', 'Трактор, комбайн', 122),
(12, 'Forklift Rentals', 'Навантажувач', 122),
(12, 'Other Transport Rentals', 'Інший транспорт', 122),
(12, 'Concrete Mixers Rentals', 'Оренда бетонозмішувачів', 123),
(12, 'Formwork Rentals', 'Оренда опалубки', 123),
(12, 'Scaffolding Rentals', 'Оренда риштувань', 123),
(12, 'Portable Toilets and Cabins Rentals', 'Оренда біотуалетів і побутовок', 123),
(12, 'Generators Rentals', 'Оренда генераторів', 123),
(12, 'Toys and Mobiles Rentals', 'Іграшки та мобілі', 128),
(12, 'Strollers and Car Seats Rentals', 'Коляски та автокрісла', 128),
(12, 'Clothing and Costumes Rentals', 'Одяг та костюми', 128),
(12, 'Other Children''s Goods Rentals', 'Інші дитячі товари', 128);
