INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(1, 'Body', 'Боді', 1),
(1, 'T-shirts and Tops', 'Майки та футболки', 1),
(1, 'Blouses and Shirts', 'Блузи і сорочки', 1),
(1, 'Sweaters, Cardigans, and Hoodies', 'Светри, кардигани, худі', 1),
(1, 'Dresses', 'Плаття', 1),
(1, 'Skirts', 'Спідниці', 1),
(1, 'Outerwear', 'Верхній одяг', 1),
(1, 'Jeans', 'Джинси', 1),
(1, 'Shorts', 'Шорти', 1),
(1, 'Trousers', 'Брюки', 1),
(1, 'Overalls', 'Комбінезони', 1),
(1, 'Women''s Blazers and Jackets', 'Жіночі піджаки та жакети', 1),
(1, 'Loungewear and Sleepwear', 'Домашній одяг та одяг для сну', 1),
(1, 'Sportswear', 'Спортивний одяг', 1),
(1, 'Swimwear', 'Купальники', 1),
(1, 'Lingerie', 'Спідня білизна', 1),
(1, 'Other Women''s Clothing', 'Інший жіночий одяг', 1),
(1, 'Boots and Ankle Boots', 'Черевики та напівчеревики', 2),
(1, 'Shoes', 'Туфлі', 2),
(1, 'Boots and Half Boots', 'Чоботи та напівчоботи', 2),
(1, 'Sneakers', 'Кросівки', 2),
(1, 'Slip-Ons', 'Кеди', 2),
(1, 'House Shoes', 'Домашне взуття', 2),
(1, 'Sports Shoes', 'Спортивне взуття', 2),
(1, 'Orthopedic Shoes', 'Ортопедичне взуття', 2),
(1, 'Sandals, Slippers, Flip-Flops', 'Босоніжки, сандалі, в''єтнамки, шльопанці', 2),
(1, 'Other Women''s Shoes', 'Інше жіноче взуття', 2),
(1, 'Bags', 'Сумки', 3),
(1, 'Jewelry', 'Ювелірні вироби', 3),
(1, 'Costume Jewelry', 'Біжутерія', 3),
(1, 'Backpacks', 'Рюкзаки', 3),
(1, 'Glasses', 'Окуляри', 3),
(1, 'Scarves and Gloves', 'Шарфи та рукавички', 3),
(1, 'Wallets, Cosmetic Bags, Cardholders', 'Гаманці, косметички, візитниці', 3),
(1, 'Belts and Waistbands', 'Ремені та пояси', 3),
(1, 'Hair Accessories', 'Аксесуари для волосся', 3),
(1, 'Umbrellas', 'Парасолі', 3),
(1, 'Ties and Bow Ties', 'Краватки та метелики', 3),
(1, 'Shoe Accessories', 'Аксесуари для взуття', 3),
(1, 'Headwear', 'Головні убори', 3),
(1, 'Other Accessories', 'Інші аксесуари', 3),
(1, 'Outerwear', 'Верхній одяг', 4),
(1, 'Blazers and Suits', 'Піджаки та костюми', 4),
(1, 'Sweaters and Pullovers', 'Кофти та светри', 4),
(1, 'Shirts and T-shirts', 'Сорочки та теніски', 4),
(1, 'T-shirts and Tank Tops', 'Футболки та майки', 4),
(1, 'Underwear', 'Спідня білизна', 4),
(1, 'Sportswear', 'Спортивний одяг', 4),
(1, 'Loungewear and Sleepwear', 'Одяг для дому та сну', 4),
(1, 'Workwear', 'Спецодяг', 4),
(1, 'Tactical Clothing', 'Тактичний одяг', 4),
(1, 'Trousers, Jeans and Shorts', 'Штани, джинси та шорти', 4),
(1, 'Other Men''s Clothing', 'Інший чоловічий одяг', 4),
(1, 'Sneakers', 'Кросівки', 5),
(1, 'Boots', 'Черевики', 5),
(1, 'Shoes', 'Туфлі', 5),
(1, 'Slip-Ons', 'Кеди', 5),
(1, 'Sandals and Slippers', 'Сандалі та шльопанці', 5),
(1, 'Moccasins and Loafers', 'Мокасини та сліпони', 5),
(1, 'Boots and Ankle Boots', 'Чоботи та напівчоботи', 5),
(1, 'House Shoes', 'Домашнє взуття', 5),
(1, 'Orthopedic Shoes', 'Ортопедичне взуття', 5),
(1, 'Other Men''s Shoes', 'Інше чоловіче взуття', 5),
(1, 'Outerwear', 'Верхній одяг', 6),
(1, 'Sweaters and Pullovers', 'Кофти та светри', 6),
(1, 'T-shirts and Tank Tops', 'Футболки та майки', 6),
(1, 'Suits', 'Костюми', 6),
(1, 'Tights and Socks', 'Колготи та шкарпетки', 6),
(1, 'Trousers, Jeans, and Leggings', 'Штани, джинси, лосіни', 6),
(1, 'Blouses and Shirts', 'Блузки та сорочки', 6),
(1, 'Skirts', 'Спідниці', 6),
(1, 'Shorts', 'Шорти', 6),
(1, 'Summer Overalls', 'Комбінезони літні', 6),
(1, 'Underwear', 'Спідня білизна', 6),
(1, 'Dresses and Sundresses', 'Сукні та сарафани', 6),
(1, 'Other Girls Clothing', 'Інший одяг для дівчаток', 6),
(1, 'Outerwear', 'Верхній одяг', 7),
(1, 'Sweaters and Pullovers', 'Кофти та светри', 7),
(1, 'T-shirts and Tank Tops', 'Футболки та майки', 7),
(1, 'Suits', 'Костюми', 7),
(1, 'Tights and Socks', 'Колготи та шкарпетки', 7),
(1, 'Trousers, Jeans and Leggings', 'Штани, джинси та лосіни', 7),
(1, 'Shirts and T-shirts', 'Сорочки та теніски', 7),
(1, 'Shorts', 'Шорти', 7),
(1, 'Overalls', 'Комбінезони', 7),
(1, 'Underwear', 'Спідня білизна', 7),
(1, 'Other Boys Clothing', 'Інший одяг для хлопчиків', 7),
(1, 'Baptism Sets', 'Набори для хрещення', 8),
(1, 'Sleeping Bags and Swaddles', 'Конверти та спальні мішки', 8),
(1, 'Suits and Sets', 'Костюми та комплекти', 8),
(1, 'Bodysuits, Rompers, and Jumpsuits', 'Боді, чоловічки, пісочники', 8),
(1, 'Crawlers, Pants, and Shorts', 'Повзунки, штани, шорти', 8),
(1, 'Shirts and Sweaters', 'Сорочечки та кофти', 8),
(1, 'Booties and Scratch Mitts', 'Пінєтки і царапки', 8),
(1, 'Dresses and Skirts', 'Плаття, сарафани і спідниці', 8),
(1, 'Outerwear', 'Верхній одяг', 8),
(1, 'T-shirts and Tank Tops', 'Футболки та майки', 8),
(1, 'Textiles', 'Текстиль', 8),
(1, 'Swimwear', 'Купальні костюми', 8),
(1, 'Tights and Socks', 'Колготки і шкарпетки', 8),
(1, 'Underwear', 'Спідня білизна', 8),
(1, 'Baby Footwear', 'Взуття для малюків', 8),
(1, 'Other Baby Items', 'Інше для малюків', 8),
(1, 'Sneakers and Slip-Ons', 'Кросівки, кеди', 9),
(1, 'Sandals, Slippers, and Flip-Flops', 'Сандалі, босоніжки, шльопки', 9),
(1, 'Boots and Ankle Boots', 'Чоботи та черевики', 9),
(1, 'Shoes', 'Туфлі', 9),
(1, 'House Shoes', 'Домашнє взуття', 9),
(1, 'Shoe Accessories', 'Аксесуари для взуття', 9),
(1, 'Other Children''s Footwear', 'Інше взуття', 9),
(1, 'Perfume', 'Парфумерія', 10),
(1, 'Facial Care', 'Догляд за обличчям', 10),
(1, 'Decorative Cosmetics', 'Декоративна косметика', 10),
(1, 'Hair Care', 'Косметика для волосся', 10),
(1, 'Body Care', 'Косметика для тіла', 10),
(1, 'Manicure and Pedicure', 'Манікюр та педікюр', 10),
(1, 'Oral Care', 'Для ротової порожнини', 10),
(1, 'Beauty Accessories', 'Аксесуари для краси', 10),
(1, 'Disinfectants', 'Дезинфікуючі засоби', 10),
(1, 'Optics', 'Оптика', 10),
(1, 'Hygiene', 'Гігієна', 10),
(1, 'Intimate Products', 'Інтимні товари', 10),
(1, 'Sun Protection/Sun Tan', 'Захист від сонця/засмага', 10),
(1, 'Medical Devices', 'Медичні прилади', 10),
(1, 'Other Beauty and Health Products', 'Інші товари для краси та здоров''я', 10);
