INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(6, 'Tableware', 'Столовий посуд', 56),
(6, 'Table Setting', 'Сервіровка стола', 56),
(6, 'Storage Containers', 'Посуд для зберігання', 56),
(6, 'Kitchenware', 'Кухонний посуд', 56),
(6, 'Cooking Utensils', 'Посуд ля приготування', 56),
(6, 'Tea and Coffee Ware', 'Посуд для чаю та кави', 56),
(6, 'Kitchen Accessories', 'Кухонне приладдя', 56),
(6, 'Barware', 'Барний посуд', 56),
(6, 'Other Kitchenware', 'Інше приладдя та посуд', 56),
(6, 'Living Room Furniture', 'Меблі для вітальні', 57),
(6, 'Bedroom Furniture', 'Меблі для спальні', 57),
(6, 'Office Furniture', 'Офісні меблі', 57),
(6, 'Kitchen Furniture', 'Кухонні меблі', 57),
(6, 'Hallway Furniture', 'Меблі для передпокою', 57),
(6, 'Bathroom Furniture', 'Меблі для ванної кімнати', 57),
(6, 'Custom Furniture', 'Меблі на замовлення', 57),
(6, 'Furniture Accessories', 'Аксесуари для меблів', 57),
(6, 'Other Furniture', 'Інше в Меблі', 57),
(6, 'Plumbing', 'Сантехніка', 58),
(6, 'Heating', 'Опалення', 58),
(6, 'Windows/Doors/Glass/Mirrors', 'Вікна / двері/ скло /дзеркала', 58),
(6, 'Electricity', 'Електрика', 58),
(6, 'Finishing and Facing Materials', 'Оздоблювальні  та облицювальні матеріали', 58),
(6, 'Metal Rolling/Armature', 'Металопрокат/арматура', 58),
(6, 'Bricks/Concrete/Blocks', 'Цегла/бетон/піноблоки', 58),
(6, 'Timber', 'Пиломатеріали', 58),
(6, 'Fasteners', 'Елементи кріплення', 58),
(6, 'Hardware', 'Фурнітура', 58),
(6, 'Ventilation', 'Вентиляція', 58),
(6, 'Wallpaper', 'Шпалери', 58),
(6, 'Decorative and Painting Materials', 'Декоративні, малярні матеріали (штукатурки, шпатлівки)', 58),
(6, 'Gate Automation', 'Автоматика для воріт', 58),
(6, 'Paints and Varnishes', 'Лакофарбові матеріали', 58),
(6, 'Other Construction/Repairs', 'Інше в Будівництво/ремонт', 58),
(6, 'All Tools', 'Все в інструменти', 59),
(6, 'Power Tools', 'Електроінструмент', 59),
(6, 'Hand Tools', 'Ручний інструмент', 59),
(6, 'Generators', 'Генератори', 59),
(6, 'Gasoline Tools', 'Бензоінструмент', 59),
(6, 'Pneumatic Tools', 'Пневмоінструмент', 59),
(6, 'Other Tools', 'Інший інструмент', 59),
(6, 'Textiles', 'Текстиль', 60),
(6, 'Lighting', 'Освітлення', 60),
(6, 'Window Decor', 'Декор вікон', 60),
(6, 'Photo Frames', 'Фоторамки', 60),
(6, 'Candles and Candle Holders', 'Свічки та підсвічники', 60),
(6, 'Aromatic Products', 'Ароматичні засоби', 60),
(6, 'Vases', 'Вази', 60),
(6, 'Boxes', 'Скриньки', 60),
(6, 'Clocks', 'Годинники', 60),
(6, 'Pictures', 'Картини', 60),
(6, 'Mirrors', 'Дзеркала', 60),
(6, 'Accessories', 'Аксесуари', 60),
(6, 'Artificial Flowers', 'Штучні квіти', 60),
(6, 'Key Holders', 'Ключниці', 60),
(6, 'Scratch Maps', 'Скретч-карти', 60),
(6, 'Posters', 'Постери', 60),
(6, 'Paintings and Icons', 'Картини та ікони', 60),
(6, 'Interior Dolls', 'Інтер''єрні ляльки', 60),
(6, 'Decorative Elements', 'Декоративні елементи', 60),
(6, 'Wall Decor', 'Настінний декор', 60),
(6, 'Other Interior Items', 'Інше в Предмети інтер''єру', 60),
(6, 'Plants and Seeds', 'Рослини та насіння', 61),
(6, 'Soils, Fertilizers, Pest Control', 'Грунти, добрива, засоби від шкідників', 61),
(6, 'Watering Systems', 'Системи поливу', 61),
(6, 'Pots and Planters', 'Горщики та кашпо', 61),
(6, 'Lighting', 'Освітлення', 61),
(6, 'Other Houseplants', 'Інше в кімнатні рослини', 61),
(6, 'Garden Equipment', 'Садова техніка', 62),
(6, 'Garden Tools', 'Садовий інвентар', 62),
(6, 'Watering Equipment', 'Обладнання для поливу', 62),
(6, 'Garden Furniture', 'Садові меблі', 62),
(6, 'Pools', 'Басейни', 62),
(6, 'Landscaping', 'Ландшафт', 62),
(6, 'Fireplaces, Stoves, Saunas', 'Каміни, печі, сауни', 62),
(6, 'Outbuildings and Utility Buildings', 'Побутівки та госпбудівлі', 62),
(6, 'Plants', 'Рослини', 62),
(6, 'Cleaning Products', 'Засоби для прибирання', 63),
(6, 'Dishwashing Products', 'Засоби для миття посуду', 63),
(6, 'Ironing Products', 'Засоби для прасування', 63),
(6, 'Washing Products', 'Засоби для прання', 63),
(6, 'Air Fresheners', 'Освіжувачі повітря', 63),
(6, 'Specialized Products', 'Спеціалізовані засоби', 63),
(6, 'Shoe Care Products', 'Засоби для взуття', 63),
(6, 'Insect Repellents', 'Засоби від комах', 63),
(6, 'Cleaning Equipment', 'Інвентар для прибирання', 63),
(6, 'Cleaning and Washing Containers', 'Ємності для прибирання та прання', 63),
(6, 'Other Cleaning Products', 'Інше в Інвентар/побутова хімія', 63),
(6, 'Storage Boxes', 'Коробки для зберігання', 64),
(6, 'Containers', 'Контейнери', 64),
(6, 'Laundry Baskets', 'Кошики для білизни', 64),
(6, 'Organizers', 'Органайзери', 64),
(6, 'Clothes Hangers', 'Вішалки', 64),
(6, 'Clothing Covers', 'Чохли для одягу', 64),
(6, 'Laundry Bags', 'Мішки для прання', 64),
(6, 'Vacuum Storage Bags', 'Вакуумні пакети для одягу', 64),
(6, 'Ironing Boards', 'Прасувальні дошки', 64),
(6, 'Clothes Dryers', 'Сушарки для білизни', 64),
(6, 'Clothespins', 'Прищіпки', 64),
(6, 'Clothing Rollers', 'Валики для одягу', 64),
(6, 'Clothing Brushes', 'Щітки для одягу', 64),
(6, 'Other Clothing Storage/Care', 'Інші товари для зберігання та догляду за одягом', 64),
(6, 'Beverages', 'Напої', 65),
(6, 'Agricultural Products', 'Сільськогосподарськи продукти', 65),
(6, 'Products for Cafes and Restaurants', 'Продукти для кафе та ресторанів', 65),
(6, 'Fish Products', 'Рибні продукти', 65),
(6, 'Gift Sets', 'Подарункові набори', 65),
(6, 'Other Food/Beverages', 'Інші продукти/напої', 65),
(6, 'Easter Goods', 'До Великодня', 66),
(6, 'Wedding Goods', 'До Весілля', 66),
(6, 'Birthday and Anniversary Goods', 'До Дня народження та юбілеїв', 66),
(6, 'Halloween Goods', 'До Хеллоуіну', 66),
(6, 'New Year Goods', 'До Нового Року', 66),
(6, 'Christmas Goods', 'До Різдва', 66),
(6, 'Other Holiday Goods', 'До інших свят та урочистих подій', 66);