INSERT INTO subcategories (category_id, name_en, name_ukr)
VALUES
(1, 'Women''s Clothing', 'Жіночий одяг'),
(1, 'Women''s Shoes', 'Жіноче взуття'),
(1, 'Accessories', 'Аксесуари'),
(1, 'Men''s Clothing', 'Чоловічий одяг'),
(1, 'Men''s Shoes', 'Чоловіче взуття'),
(1, 'Girls Clothing', 'Одяг для дівчаток'),
(1, 'Boys Clothing', 'Одяг для хлопчиків'),
(1, 'For Babies', 'Для малюків'),
(1, 'Children''s Shoes', 'Дитяче взуття'),
(1, 'Beauty and Health', 'Краса та здоров''я'),
(1, 'Other Fashion Items', 'Інші товари в Мода та стиль'),
(2, 'Strollers and Car Seats', 'Коляски та автокрісла'),
(2, 'Toys', 'Іграшки'),
(2, 'School Supplies', 'Товари для школярів'),
(2, 'Children''s Furniture', 'Дитячі меблі'),
(2, 'Children''s Transport', 'Дитячий транспорт'),
(2, 'Feeding', 'Годування'),
(2, 'Children''s Hygiene', 'Дитяча гігієна'),
(2, 'Children''s Accessories', 'Аксесуари для дітей'),
(2, 'Outdoor Activities', 'Активний відпочинок'),
(2, 'Other Children''s Goods', 'Інші дитячі товари'),
(3, 'Books and Magazines', 'Книги та журнали'),
(3, 'Collectibles/Antiques', 'Колекціонування/антикваріат'),
(3, 'Tourism and Camping', 'Туризм і кемпінг'),
(3, 'Fishing', 'Риболовля'),
(3, 'Musical Instruments', 'Музичні інструменти'),
(3, 'Leisure Goods', 'Товари для дозвілля'),
(3, 'Boats and Accessories', 'Човни та аксесуари'),
(3, 'Drones and Accessories', 'Квадрокоптери та аксесуари'),
(3, 'Militaria', 'Мілітарія'),
(3, 'Sports Goods', 'Спортивні товари'),
(3, 'Tickets', 'Квитки'),
(3, 'Other Hobbies and Sports', 'Інше в хоббі та спорт'),
(4, 'Passenger Cars', 'Легкові авто'),
(4, 'Trucks', 'Вантажні авто'),
(4, 'Moto', 'Мото'),
(4, 'Agricultural Machinery', 'Сільгосптехніка'),
(4, 'Special Machinery', 'Спецтехніка'),
(4, 'Spare Parts', 'Запчастини'),
(4, 'Automotive Electronics', 'Автомобільна електроніка'),
(4, 'Accessories', 'Аксесуари'),
(4, 'Car Chemicals and Oils', 'Автохімія та автомастила'),
(4, 'Other in Transport', 'Інше в транспорт'),
(5, 'Phones and Accessories', 'Телефони та аксесуари'),
(5, 'Audio Equipment', 'Аудіотехніка'),
(5, 'Computers and Components', 'Комп''ютери та комплектуючі'),
(5, 'Games and Consoles', 'Ігри та ігрові приставки'),
(5, 'Home Appliances', 'Техніка для дому'),
(5, 'Kitchen Appliances', 'Техніка для кухні'),
(5, 'TV/Video Equipment', 'ТВ/ Відеотехніка'),
(5, 'Photo/Video', 'Фото/відео'),
(5, 'Tablets/E-books', 'Планшети / ел. книги'),
(5, 'Climate Equipment', 'Кліматичне обладнання'),
(5, 'Personal Care', 'Індивідуальний догляд'),
(5, 'Other in Electronics', 'Інше в електроніка'),
(6, 'Dishes/Kitchenware', 'Посуд/кухонне приладдя'),
(6, 'Furniture', 'Меблі'),
(6, 'Construction/Repairs', 'Будівництво/ремонт'),
(6, 'Tools', 'Інструменти'),
(6, 'Interior Items', 'Предмети інтер''єру'),
(6, 'Houseplants', 'Кімнатні рослини'),
(6, 'Garden/Cottage/Orchard', 'Сад/дача/огород'),
(6, 'Inventory/Cleaning Products', 'Інвентар/побутова хімія'),
(6, 'Clothing Storage/Care', 'Зберігання та догляд за одягом'),
(6, 'Food/Beverages', 'Продукти/напої'),
(6, 'Holiday Goods', 'Товари для свят'),
(6, 'Other Home Goods', 'Інші товари для дому'),
(7, 'Rent', 'Оренда'),
(7, 'Sale', 'Продаж'),
(7, 'Real Estate Abroad', 'Нерухомість закордоном'),
(7, 'Other in Real Estate', 'Інше в нерухомість'),
(8, 'Pet Supplies and Accessories', 'Зоотовари та аксесуари'),
(8, 'Food, Vitamins, Supplements', 'Корма, вітаміни, добавки'),
(8, 'Animals', 'Тварини'),
(8, 'Other in Pet Products', 'Інше'),
(9, 'Beauty/Health', 'Краса/здоров''я'),
(9, 'Transport and Special Machinery Services', 'Перевезення та послуги спецтехніки'),
(9, 'Business Equipment', 'Обладнання для бізнесу'),
(9, 'Construction and Repairs', 'Будівництво та ремонт'),
(9, 'Household Services', 'Побутові послуги'),
(9, 'Education/Sports Services', 'Послуги освіти/ спорту'),
(9, 'Auto/Moto Services', 'Авто/мотопослуги'),
(9, 'Technical Repair and Maintenance', 'Ремонт та обслуговування техніки'),
(9, 'Business Services', 'Ділові послуги'),
(9, 'Event Organization', 'Організація свят'),
(9, 'Business for Sale', 'Продаж бізнесу'),
(9, 'Photo/Video Shooting', 'Фото/відеозйомка'),
(9, 'Cleaning Services', 'Клінінг'),
(9, 'Waste Recycling', 'Прийом вторсировини'),
(9, 'Pet Services', 'Послуги для тварин'),
(9, 'Child/Elderly Care', 'Догляд за дітьми/літніми людьми'),
(9, 'Funeral Services', 'Ритуальні послуги'),
(9, 'Tourism/Immigration', 'Туризм / іміграція'),
(9, 'Other Services', 'Інші послуги'),
(10, 'Career Start/Students', 'Початок кар''єри/студенти'),
(10, 'Administration/HR/Secretariat', 'Адміністрація / HR / Секретаріат'),
(10, 'Car Repair/Wash', 'СТО / автомийки'),
(10, 'Part-Time Jobs', 'Часткова зайнятість'),
(10, 'Trade/Sales/Purchases', 'Торгівля / продажі / закупки'),
(10, 'Manufacturing/Industrial Jobs', 'Виробництво/робітничі спеціальності'),
(10, 'Hospitality/Tourism', 'Готельно-ресторанний бізнес/туризм'),
(10, 'Logistics/Warehousing/Delivery', 'Логістика /склад /доставка'),
(10, 'Construction/Repairs', 'Будівництво / ремонт'),
(10, 'Cleaning/Domestic Staff', 'Клінінг/домашній персонал'),
(10, 'Beauty/Fitness/Sports', 'Краса / фітнес / спорт'),
(10, 'Jobs Abroad', 'Робота закордоном'),
(10, 'Security', 'Охорона / безпека'),
(10, 'Advertising/PR/Design', 'Реклама / PR / дизайн'),
(10, 'Call Centers/Telecommunications', 'Колл центри / телекомунікації'),
(10, 'Education/Translation', 'Освіта / переклад'),
(10, 'Culture/Art/Entertainment', 'Культура /мистетцтво / розваги'),
(10, 'Accounting', 'Бухгалтерія'),
(10, 'Real Estate', 'Нерухомість'),
(10, 'Agriculture/Forestry', 'Сільське і лісове господарство / агробізнес'),
(10, 'IT/Computers', 'IT/комп''ютери'),
(10, 'Medicine/Pharmacy', 'Медицина / Фармацевтика'),
(10, 'Banks/Finance/Insurance/Legal', 'Банки/фінанси / страхування / юриспруденція'),
(10, 'Other Job Sectors', 'Інші сфери занять'),
(11, 'Help', 'Допомога'),
(11, 'Give Away for Free', 'Віддам безкоштовно'),
(11, 'Exchange', 'Обмін'),
(12, 'Transport Rentals', 'Оренда транспорту'),
(12, 'Equipment Rentals', 'Оренда обладнання'),
(12, 'Tool Rentals', 'Прокат інструментів'),
(12, 'Event Goods Rentals', 'Прокат товарів для заходів'),
(12, 'Clothing and Accessories Rentals', 'Прокат одягу та аксесуарів'),
(12, 'Electronics Rentals', 'Прокат техніки та електроніки'),
(12, 'Children''s Goods Rentals', 'Прокат дитячих товарів'),
(12, 'Medical Goods Rentals', 'Прокат медицинських товарів'),
(12, 'Tourism and Sports Goods Rentals', 'Прокат туристичних та спорт товарів'),
(12, 'Other Rentals', 'Інші товари на прокат');
