INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(7, 'Apartments', 'Квартири', 68),
(7, 'Rooms', 'Кімнати', 68),
(7, 'Houses', 'Будинки', 68),
(7, 'Cottages', 'Дачі', 68),
(7, 'Vacation Homes', 'Курортні будинки', 68),
(7, 'Daily Rental Housing', 'Подобова оренда житла', 68),
(7, 'Land', 'Земля', 68),
(7, 'Garages and Parking', 'Гаражі  та парковки', 68),
(7, 'Commercial Real Estate', 'Комерційна нерухомість', 68),
(7, 'Coworking Spaces', 'Коворкінги', 68),
(7, 'Apartments', 'Квартири', 69),
(7, 'Rooms', 'Кімнати', 69),
(7, 'Houses', 'Будинки', 69),
(7, 'Cottages', 'Дачі', 69),
(7, 'Vacation Homes', 'Курортні будинки', 69),
(7, 'Land', 'Земля', 69),
(7, 'Garages and Parking', 'Гаражі  та парковки', 69),
(7, 'Commercial Real Estate', 'Комерційна нерухомість', 69),
(7, 'Other', 'Інше', 69),
(7, 'Apartments Abroad', 'Квартири', 70),
(7, 'Houses Abroad', 'Будинки', 70),
(7, 'Commercial Real Estate Abroad', 'Комерційна нерухомість', 70),
(7, 'Other Abroad', 'Інше', 70);