DELETE FROM categories;

INSERT INTO categories (id, name_en, name_ukr)
VALUES
    (1, 'Help', 'Допомога'),
    (2, 'Children''s World', 'Дитячий світ'),
    (3, 'Real Estate', 'Нерухомість'),
    (4, 'Auto', 'Авто'),
    (5, 'Transport Parts', 'Запчастини для транспорту'),
    (6, 'Jobs', 'Робота'),
    (7, 'Pets', 'Тварини'),
    (8, 'Home & Garden', 'Дім і сад'),
    (9, 'Electronics', 'Електроніка'),
    (10, 'Business & Services', 'Бізнес та послуги'),
    (11, 'Rentals', 'Оренда та прокат'),
    (12, 'Fashion & Style', 'Мода і стиль'),
    (13, 'Hobbies, Recreation & Sports', 'Хобі, відпочинок і спорт'),
    (14, 'Give Away for Free', 'Віддам безкоштовно'),
    (15, 'Exchange', 'Обмін'),
    (16, 'Auto for the Military', 'Авто для війська'),
    (17, 'Service in the Defense Forces', 'Служба в Силах оборони');

INSERT INTO subcategories (category_id, name_en, name_ukr)
VALUES
    (1, 'Assistance Required', 'Потрібна допомога'),
    (2, 'Assistance Offered', 'Пропоную допомогу'),
    (2, 'Children''s clothing', 'Дитячий одяг'),
    (2, 'Children''s footwear', 'Дитяче взуття'),
    (2, 'Children''s strollers', 'Дитячі коляски'),
    (2, 'Children''s car seats', 'Дитячі автокрісла'),
    (2, 'Feeding', 'Годування'),
    (2, 'Children''s furniture', 'Дитячі меблі'),
    (2, 'Toys', 'Іграшки'),
    (2, 'Goods for schoolchildren', 'Товари для школярів'),
    (2, 'Other children''s goods', 'Інші дитячі товари'),
    (2, 'Children''s transport', 'Дитячий транспорт'),
    (3, 'Apartments', 'Квартири'),
    (3, 'Rooms', 'Кімнати'),
    (3, 'Houses', 'Будинки'),
    (3, 'Land', 'Земля'),
    (3, 'Commercial Real Estate', 'Комерційна нерухомість'),
    (3, 'Garages, Parking', 'Гаражі, парковки'),
    (3, 'Daily Rental', 'Подобова оренда житла'),
    (3, 'Real Estate Abroad', 'Нерухомість за кордоном'),
    (4, 'Passenger cars', 'Легкові автомобілі'),
    (4, 'Trucks', 'Вантажні автомобілі'),
    (4, 'Buses', 'Автобуси'),
    (4, 'Motorcycles', 'Мото'),
    (4, 'Special machinery', 'Спецтехніка'),
    (4, 'Agricultural machinery', 'Сільгосптехніка'),
    (4, 'Water transport', 'Водний транспорт'),
    (4, 'Cars from Poland', 'Автомобілі з Польщі'),
    (4, 'Trailers / Mobile homes', 'Причепи / будинки на колесах'),
    (4, 'Trucks and special machinery from Poland', 'Вантажівки та спецтехніка з Польщі'),
    (4, 'Other transport', 'Інший транспорт'),
    (5, 'Auto parts', 'Автозапчастини'),
    (5, 'Auto accessories', 'Аксесуари для авто'),
    (5, 'Car audio and multimedia', 'Автозвук та мультимедіа'),
    (5, 'Tires, wheels and rims', 'Шини, диски і колеса'),
    (5, 'GPS navigators / Video recorders', 'GPS-навігатори / відеореєстратори'),
    (5, 'Transport for parts / Auto dismantling', 'Транспорт на запчастини / авторозбірки'),
    (5, 'Motorcycle parts', 'Мотозапчастини'),
    (5, 'Motorcycle equipment', 'Мотоекіпірування'),
    (5, 'Motorcycle accessories', 'Мотоаксесуари'),
    (5, 'Lubricants and auto chemicals', 'Мастила та автохімія'),
    (5, 'Parts for other machinery', 'Запчастини для іншої техніки'),
    (7, 'Free (animals and breeding)', 'Безкоштовно / тварини і в''язка'),
    (7, 'Dogs', 'Собаки'),
    (7, 'Cats', 'Коти'),
    (7, 'Aquaristics', 'Акваріумістика'),
    (7, 'Birds', 'Пташки'),
    (7, 'Rodents', 'Гризуни'),
    (7, 'Reptiles', 'Рептилії'),
    (7, 'Agricultural animals', 'Сільгосп тварини'),
    (7, 'Other animals', 'Інші тварини'),
    (7, 'Pet supplies', 'Зоотовари'),
    (7, 'Breeding', 'В''язка'),
    (7, 'Lost and found office', 'Бюро знахідок'),
    (8, 'Stationery / Consumables', 'Канцтовари / витратні матеріали'),
    (8, 'Furniture', 'Меблі'),
    (8, 'Food / Beverages', 'Продукти харчування / напої'),
    (8, 'Garden', 'Сад / город'),
    (8, 'Interior items', 'Предмети інтер''єру'),
    (8, 'Construction / Renovation', 'Будівництво / ремонт'),
    (8, 'Tools', 'Інструменти'),
    (8, 'House plants', 'Кімнатні рослини'),
    (8, 'Dishes / Kitchen utensils', 'Посуд / кухонне приладдя'),
    (8, 'Garden tools', 'Садовий інвентар'),
    (8, 'Household inventory / Household chemicals', 'Господарський інвентар / побутова хімія'),
    (8, 'Other home goods', 'Інші товари для дому'),
    (9, 'Phones and accessories', 'Телефони та аксесуари'),
    (9, 'Computers and components', 'Комп''ютери та комплектуючі'),
    (9, 'Photo / Video', 'Фото / відео'),
    (9, 'TV / Video equipment', 'Тв / відеотехніка'),
    (9, 'Audio equipment', 'Аудіотехніка'),
    (9, 'Games and gaming consoles', 'Ігри та ігрові приставки'),
    (9, 'Tablets / e-readers and accessories', 'Планшети / ел. книги та аксесуари'),
    (9, 'Laptops and accessories', 'Ноутбуки та аксесуари'),
    (9, 'Home appliances', 'Техніка для дому'),
    (9, 'Kitchen appliances', 'Техніка для кухні'),
    (9, 'Climate equipment', 'Кліматичне обладнання'),
    (9, 'Personal care', 'Індивідуальний догляд'),
    (9, 'Accessories and components', 'Аксесуари й комплектуючі'),
    (9, 'Other electronics', 'Інша електроніка'),
    (9, 'Repair and maintenance of equipment', 'Ремонт та обслуговування техніки'),
    (10, 'Auto / Moto Services', 'Авто / мото послуги'),
    (10, 'Beauty / Health', 'Краса / здоров''я'),
    (10, 'Child and Elderly Care', 'Догляд за дітьми та літніми людьми'),
    (10, 'Household Services', 'Побутові послуги'),
    (10, 'Cleaning', 'Клінінг'),
    (10, 'Education and Sports Services', 'Послуги освіти та спорту'),
    (10, 'Transportation and Special Equipment Services', 'Перевезення та послуги спецтехніки'),
    (10, 'Photography and Videography', 'Фото та відеозйомка'),
    (10, 'Event Organization', 'Організація свят'),
    (10, 'Repair and Maintenance of Equipment', 'Ремонт та обслуговування техніки'),
    (10, 'Construction and Renovation', 'Будівництво та ремонт'),
    (10, 'Raw Materials / Supplies', 'Сировина / матеріали'),
    (10, 'Recycling Services', 'Прийом вторсировини'),
    (10, 'Tourism / Immigration Services', 'Туризм / іміграція'),
    (10, 'Business Services', 'Ділові послуги'),
    (10, 'Business for Sale', 'Продаж бізнесу'),
    (10, 'Business Equipment for Sale', 'Продаж обладнання для бізнесу'),
    (10, 'Animal Services', 'Послуги для тварин'),
    (10, 'Funeral Services', 'Ритуальні послуги'),
    (10, 'Other Services', 'Інші послуги'),
    (11, 'Rental of transport and special equipment', 'Оренда транспорту та спецтехніки'),
    (11, 'Bicycle and moto rental', 'Прокат велосипедів і мото'),
    (11, 'Equipment rental', 'Оренда обладнання'),
    (11, 'Tool rental', 'Прокат інструментів'),
    (11, 'Medical supplies rental', 'Прокат товарів мед призначення'),
    (11, 'Technology and electronics rental', 'Прокат техніки та електроніки'),
    (11, 'Event equipment rental', 'Прокат товарів для заходів'),
    (11, 'Sports and tourism goods rental', 'Прокат спорт і туристичних товарів'),
    (11, 'Clothing and accessories rental', 'Прокат одягу та аксесуарів'),
    (11, 'Children''s clothing and goods rental', 'Прокат дитячого одягу та товарів'),
    (11, 'Other rental goods', 'Інші товари на прокат'),
    (12, 'Women''s Clothing', 'Жіночий одяг'),
    (12, 'Women''s Shoes', 'Жіноче взуття'),
    (12, 'Men''s Clothing', 'Чоловічий одяг'),
    (12, 'Men''s Shoes', 'Чоловіче взуття'),
    (12, 'Women''s Lingerie and Swimwear', 'Жіноча білизна та купальники'),
    (12, 'Men''s Underwear and Swimwear', 'Чоловіча білизна та плавки'),
    (12, 'Headwear', 'Головні убори'),
    (12, 'Wedding', 'Для весілля'),
    (12, 'Wristwatches', 'Наручні годинники'),
    (12, 'Accessories', 'Аксесуари'),
    (12, 'Maternity Wear', 'Одяг для вагітних'),
    (12, 'Beauty / Health', 'Краса / здоров''я'),
    (12, 'Gifts', 'Подарунки'),
    (12, 'Specialty Clothing, Shoes and Accessories', 'Спецодяг, спецвзуття та аксесуари'),
    (12, 'Miscellaneous Fashion', 'Мода різне'),
    (13, 'Antiques / Collections', 'Антикваріат / колекції'),
    (13, 'Musical Instruments', 'Музичні інструменти'),
    (13, 'Sports / Recreation', 'Спорт / відпочинок'),
    (13, 'Bicycles', 'Вело'),
    (13, 'Militaria', 'Мілітарія'),
    (13, 'Drones and Accessories', 'Квадрокоптери та аксесуари'),
    (13, 'Books / Magazines', 'Книги / журнали'),
    (13, 'CDs / DVDs / Vinyls', 'CD / DVD / Платівки'),
    (13, 'Tickets', 'Квитки'),
    (13, 'Carpooling', 'Пошук попутників'),
    (13, 'Band / Musician Finder', 'Пошук гуртів / музикантів'),
    (13, 'Other', 'Інше')

