INSERT INTO subcategories (category_id, name_en, name_ukr, parent_id) VALUES
(8, 'Pet Dishes', 'Посуд для тварин', 72),
(8, 'Toys', 'Іграшки', 72),
(8, 'Scratching Posts', 'Кігтеточки', 72),
(8, 'Cages and Accessories', 'Клітки та аксесуари', 72),
(8, 'Beds and Houses', 'Спальні місця та будиночки', 72),
(8, 'Accessories', 'Аксесуари', 72),
(8, 'Veterinary Products', 'Ветеренарні товари', 72),
(8, 'Other Pet Accessories', 'Інше', 72),
(8, 'Cat Food', 'Корма для котів', 73),
(8, 'Dog Food', 'Корма для собак', 73),
(8, 'Bird Food', 'Корма для птахів', 73),
(8, 'Rodent Food', 'Корма для гризунів', 73),
(8, 'Fish Food', 'Корма для риб', 73),
(8, 'Reptile Food', 'Корма для рептилій', 73),
(8, 'Vitamins and Treats', 'Вітаміни та ласощі для тварин', 73),
(8, 'Dogs', 'Собаки', 74),
(8, 'Cats', 'Коти', 74),
(8, 'Birds', 'Птахи', 74),
(8, 'Farm Animals', 'Сільгосптварини', 74),
(8, 'Aquariums', 'Акваріумістика', 74),
(8, 'Rodents', 'Гризуни', 74),
(8, 'Other Animals', 'Інші тварини', 74),
(8, 'Lost and Found Bureau', 'Бюро знахідок', 74);
