name: Code Review (AI PR Reviewer)

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AI PR Review and Summary
        uses: coderabbitai/ai-pr-reviewer@v1.11.0
        with:
          debug: false
          review_simple_changes: true
          review_comment_lgtm: true
          review_comment_in_diff: true
          summarize_changes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
